# NOTE: update this with your service name
service: quizz-o-tron-api

# Create an optimized package for our functions
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3

functions:
  api:
    handler: lambda.handler
    events: 
      - http:
          path: /{path+}
          method: ANY
          cors: true
    environment:
      APIG_URL:
        !Join
          - ''
          - - 'https://'
            - !Ref ApiGatewayRestApi
            - '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}'